Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    # 自定义运维操作
    CustomOperations:
      Actions:
        - Type: OOS
          Name: 升级服务端版本
          Operator: All
          TemplateNames:
            - ECS
          TemplateUrl: custom_operations/upgrade_server_version.yaml
        - Type: OOS
          Name: 重启服务
          Operator: All
          TemplateNames:
            - ECS
          TemplateUrl: custom_operations/restart_server.yaml
    StatusOperationConfigs:
      - TemplateName: ECS
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ##变配部分
    ModifyParametersConfig:
      - TemplateName: ECS
        Operation:
          - Name: 修改游戏参数
            Description: 修改游戏参数
            Type: Custom
            Parameters:
              - ServerName
              - ServerPassword
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  #部署相关
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: ECS
          Url: 'ros_templates/template.yaml'
          ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
          AllowedRegions:
            - ap-southeast-1
      ArtifactRelation:
        windows:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ECS
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
    - Locale: zh-CN
      ShortDescription: demo
      Image: 'resources/icons/service_logo.png'
#部署物信息相关
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: wusuo
    Description: Enshrouded_image
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: m-t4nao7n69ed5vvcmevl7
    SystemDiskSize: 100
    InstanceType: ecs.g7.large
    InternetMaxBandwidthOut: 100
    CommandType: RunPowerShellScript
    Timeout: 10800
    CommandContent: |-
      Start-Process "C:\Program Files\EnshroudedServer\steam\steamcmd.exe" -ArgumentList "+login anonymous +app_update 2278520 validate +quit" -Wait

